import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, ExternalLink, FileImage, Menu, Sparkles, X } from 'lucide-react'
import { templates } from './data'

export default function PublicHome() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [selectedTemplate, setSelectedTemplate] = useState(templates[0].id)
  const selected = templates.find((template) => template.id === selectedTemplate) ?? templates[0]

  return <main className="public-home">
    <header className="public-nav"><a className="public-brand" href="/"><span><Sparkles size={16} /></span><strong>invitarte</strong><small>estudio digital</small></a><nav className={menuOpen ? 'public-nav-open' : ''}><a href="#modelos" onClick={() => setMenuOpen(false)}>Modelos</a><a href="#como-funciona" onClick={() => setMenuOpen(false)}>Cómo funciona</a><a href="#planes" onClick={() => setMenuOpen(false)}>Planes</a><a className="nav-admin" href="/maximo1822">Administrar <ExternalLink size={14} /></a></nav><button className="icon-button public-menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menú">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></header>
    <section className="public-hero"><div className="hero-copy"><p className="eyebrow">INVITACIONES DIGITALES CON INTENCIÓN</p><h1>Una fecha importante merece <em>una experiencia.</em></h1><p>Creamos invitaciones digitales elegantes, interactivas y listas para compartir. Diseñadas para que cada celebración empiece mucho antes del evento.</p><div className="hero-actions"><a className="primary-button" href="#modelos">Explorar modelos <ArrowRight size={17} /></a><a className="quiet-link" href="#como-funciona">Conocé cómo funciona <ArrowRight size={15} /></a></div><div className="hero-proof"><span><Check size={14} /> Responsive</span><span><Check size={14} /> RSVP integrado</span><span><Check size={14} /> Link propio</span></div></div><div className="hero-card" style={{ background: selected.preview }}><span className="hero-card-label">Vista previa · {selected.category}</span><div className="hero-card-content"><small>Una celebración para</small><strong>Mariana<br />y Tomás</strong><em>{selected.name}</em></div><div className="hero-card-footer">Deslizá para descubrir <ArrowRight size={14} /></div></div></section>
    <section className="public-section" id="modelos"><div className="public-section-heading"><div><p className="eyebrow">DISEÑOS QUE SE SIENTEN PROPIOS</p><h2>Elegí el tono de tu celebración</h2></div><p>Cada modelo se adapta a tus nombres, colores, información y forma de celebrar.</p></div><div className="model-selector"><div className="model-list">{templates.map((template) => <button className={selectedTemplate === template.id ? 'model-option selected' : 'model-option'} key={template.id} onClick={() => setSelectedTemplate(template.id)}><span style={{ background: template.preview }} /><div><b>{template.name}</b><small>{template.category} · {template.mood}</small></div><ChevronDown size={15} /></button>)}</div><div className="model-preview" style={{ background: selected.preview }}><span>{selected.category}</span><div><small>Una fecha para recordar</small><strong>Tu historia<br />empieza acá</strong><em>{selected.name}</em></div></div></div></section>
    <section className="public-section process-section" id="como-funciona"><div className="public-section-heading"><div><p className="eyebrow">SIMPLE PARA VOS</p><h2>De la idea al link</h2></div><p>Nos ocupamos del diseño y la puesta a punto para que vos te ocupes de disfrutar.</p></div><div className="process-grid"><Process number="01" title="Contanos tu idea" copy="Elegís el modelo y nos compartís la información de tu evento." /><Process number="02" title="Lo hacemos tuyo" copy="Personalizamos textos, colores, fotos y cada detalle importante." /><Process number="03" title="Compartís la fecha" copy="Recibís un link propio para enviar por WhatsApp y redes." /></div></section>
    <section className="public-cta" id="planes"><div><p className="eyebrow">TU PRÓXIMO MOMENTO</p><h2>Empecemos a crear algo que quieras volver a mirar.</h2></div><a className="primary-button" href="mailto:hola@invitacionesdigitales.com?subject=Quiero%20mi%20invitación">Quiero mi invitación <ArrowRight size={17} /></a></section>
    <footer className="public-footer"><span>© 2026 invitarte</span><span>Invitaciones digitales para momentos reales</span><a href="/maximo1822">Acceso administrativo</a></footer>
  </main>
}

function Process({ number, title, copy }: { number: string; title: string; copy: string }) { return <article className="process-card"><span>{number}</span><FileImage size={19} /><h3>{title}</h3><p>{copy}</p></article> }
